# Lint Spec Ledger Workflow Configuration
name: "lint-spec-ledger"
description: "Validate the Spec Ledger for orphan references, duplicate IDs, and basic coverage gaps"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/{bmad_folder}/bmm/config.yaml"
project_name: "{config_source}:project_name"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Module path and component files
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/spec-ledger/lint-spec-ledger"
instructions: "{installed_path}/instructions.md"

# Spec Ledger location
spec_ledger_folder: "{output_folder}/spec-ledger"
spec_ledger_file: "{spec_ledger_folder}/spec-ledger.json"
spec_ledger_schema: "{project-root}/{bmad_folder}/bmm/workflows/spec-ledger/spec-ledger-sheets-schema.json"

# Output files
lint_report_file: "{output_folder}/spec-ledger-lint-report.md"
default_output_file: "{lint_report_file}"

standalone: true

web_bundle:
  name: "lint-spec-ledger"
  description: "Validate the Spec Ledger for orphan references, duplicate IDs, and basic coverage gaps"
  author: "BMad"
  instructions: "{bmad_folder}/bmm/workflows/spec-ledger/lint-spec-ledger/instructions.md"
  web_bundle_files:
    - "{bmad_folder}/bmm/workflows/spec-ledger/lint-spec-ledger/instructions.md"
    - "{bmad_folder}/bmm/workflows/spec-ledger/spec-ledger-sheets-schema.json"

